apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gateway-api
spec:
  source:
    repoURL: https://github.com/kubernetes-sigs/gateway-api
    targetRevision: v1.2.1
    path: config/crd/standard
  destination:
    server: "https://kubernetes.default.svc"
    namespace: argo-cd
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
      - ApplyOutOfSyncOnly=true
    retry:
      limit: 3
      backoff:
        duration: 15s
        factor: 2
        maxDuration: 3m
