#apiVersion: cert-manager.io/v1
#kind: ClusterIssuer
#metadata:
#  name: letsencrypt
#spec:
#  acme:
#    server: https://acme-v02.api.letsencrypt.org/directory
#    email: i.bacangan@gmail.com
#    privateKeySecretRef:
#      name: letsencrypt-account-key
#    solvers:
#      - selector:
#          dnsZones:
#            - "trial.studio"
#        dns01:
#          route53:
#            region: us-east-2
#            hostedZoneID: Z06285332QCWSWF1RDQBK
#            accessKeyIDSecretRef:
#              name: aws-keys
#              key: access_key
#            secretAccessKeySecretRef:
#              name: aws-keys
#              key: secret_key
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: vault
spec:
  vault:
    server: https://vault.trial.studio
    path: pki_int/sign/trialstudio
    auth:
      kubernetes:
        role: cert-manager
        mountPath: /v1/auth/kubernetes
        serviceAccountRef:
          name: vault-cert-manager
          audiences:
            - "external-secrets-operator"