apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-cert-manager
---
apiVersion: generators.external-secrets.io/v1alpha1
kind: VaultDynamicSecret
metadata:
  name: aws-keys
spec:
  path: /aws/creds/route53-dns-challenge
  provider:
    server: "https://vault.trial.studio"
    auth:
      kubernetes:
        mountPath: kubernetes
        role: cert-manager
        serviceAccountRef:
          name: vault-cert-manager
          audiences:
            - "external-secrets-operator"
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: aws-keys
spec:
  refreshInterval: 16h
  target:
    name: aws-keys
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: VaultDynamicSecret
          name: aws-keys
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: create-service-account-token
rules:
  - verbs: ["create"]
    resources: ["serviceaccounts/token"]
    apiGroups: [""]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: vault-cert-manager
roleRef:
  apiGroup: rbac.authorization.k8s.io/v1
  kind: Role
  name: create-service-account-token
subjects:
  - kind: ServiceAccount
    name: vault-cert-manager
