apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: trial-studio-gateway
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  gatewayClassName: cilium
  listeners:
    - name: https
      hostname: "*.trial.studio"
      port: 443
      protocol: HTTPS
      tls:
        mode: Terminate
        certificateRefs:
          - name: trial-studio-tls
      allowedRoutes:
        namespaces:
          from: All