{{ if .Capabilities.APIVersions.Has "argoproj.io/v1alpha1" -}}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gateway-crd
spec:
  source:
    repoURL: https://github.com/kubernetes-sigs/gateway-api.git
    ref: v1.3
    path: config/crd/standard
  destination:
    server: "https://kubernetes.default.svc"
  project: default
  syncPolicy:
    automated:
      selfHeal: false
      allowEmpty: false
      prune: false
    syncOptions:
      - ServerSideApply=true
      - FailOnSharedResource=true
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - RespectIgnoreDifferences=true
    retry:
      backoff:
        duration: 30s
        factor: 2
        maxDuration: 3m0s
      limit: 3
{{ end }}