{{ if .Capabilities.APIVersions.Has "gateway.networking.k8s.io/v1" -}}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: argocd
spec:
  parentRefs:
    - name: trial-studio-gateway
      namespace: istio-ingress
  hostnames: ["argocd.trial.studio"]
  rules:
    - backendRefs:
        - name: argocd-server
          port: 443
  {{ end }}