apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-cert-manager
---
apiVersion: generators.external-secrets.io/v1alpha1
kind: VaultDynamicSecret
metadata:
  name: cert-manager
spec:
  path: /aws-daily/creds/cert-manager
  method: GET
  provider:
    server: "http://vault-active.vault:8200"
    auth:
      kubernetes:
        mountPath: kubernetes
        role: cert-manager
        serviceAccountRef:
          name: vault-cert-manager
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: letsencrypt
spec:
  refreshInterval: 16h
  target:
    name: letsencrypt
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: VaultDynamicSecret
          name: cert-manager-vault-secret
