apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-cert-manager
---
apiVersion: generators.external-secrets.io/v1alpha1
kind: VaultDynamicSecret
metadata:
  name: aws-keys
spec:
  path: /daily/creds/route53-dns-challenge
  provider:
    server: "https://vault.trial.studio"
    auth:
      kubernetes:
        mountPath: kubernetes
        role: cert-manager
        serviceAccountRef:
          name: vault-cert-manager
          audiences:
            - "external-secrets-operator"
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: aws-keys
spec:
  refreshInterval: 16h
  target:
    name: aws-keys
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: VaultDynamicSecret
          name: aws-keys
