{{ if .Capabilities.APIVersions.Has "gateway.networking.k8s.io/v1" -}}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: argo-workflows
spec:
  parentRefs:
    - name: trial-studio-gateway
      namespace: istio-ingress
  hostnames: ["argo-workflows.trial.studio"]
  rules:
    - backendRefs:
        - name: argo-workflows-server
          port: 2746
  {{ end }}