apiVersion: v1
kind: ServiceAccount
metadata:
  name: rbac-default
  annotations:
    workflows.argoproj.io/rbac-rule: "true"
    workflows.argoproj.io/rbac-rule-precedence: "0"
---
apiVersion: v1
kind: Secret
metadata:
  name: rbac-default.service-account-token
  annotations:
    kubernetes.io/service-account.name: rbac-default
type: kubernetes.io/service-account-token
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: argo-workflow:custom:rbac-default
roleRef:
  name: argo-workflows-view
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: rbac-default
    namespace: argo-workflows