headlamp:
  ingress:
    enabled: true
    hosts:
      - host: headlamp.trial.studio
        paths:
          - path: /
            type: Prefix
    ingressClassName: istio
  config:
    oidc:
      clientID: "kubernetes"
      clientSecret: c8E3XscWQko25un2ob5CZzCyuOM97Nck
      issuerURL: https://keycloak.trial.studio/realms/onprem