role: Agent

customConfig:
  data_dir: /vector-data-dir
  api:
    enabled: true
    address: 0.0.0.0:8686
  sources:
    kubernetes:
      type: kubernetes_logs
  sinks:
    elasticsearch:
      type: elasticsearch
      inputs: [ kubernetes ]
      endpoints: [ http://victoria-logs/insert/elasticsearch/ ]
      mode: bulk
      api_version: v8
      compression: gzip
      healthcheck:
        enabled: false
      request:
        headers:
          VL-Stream-Fields: source_type,label.com.docker.compose.service
          VL-Time-Field: timestamp
          VL-Msg-Field: message,msg,_msg,message.message,message.log
          AccountID: "0"
          ProjectID: "0"