role: Agent

customConfig:
  data_dir: /vector-data-dir
  api:
    enabled: true
    address: 0.0.0.0:8686
  sources:
    kubernetes:
      type: kubernetes_logs
      namespace_annotation_fields:
        namespace_labels: ""
      node_annotation_fields:
        node_labels: ""
      pod_annotation_fields:
        pod_annotations: ""
        pod_labels: ""
        pod_ip: ""
        pod_ips: ""
        pod_node_name: ""
        pod_owner: ""
        pod_uid: ""
        container_id: ""
        container_image_id: ""
  sinks:
    elasticsearch:
      type: elasticsearch
      inputs: [ kubernetes ]
      endpoints: [ https://victoria-logs.trial.studio/insert/elasticsearch/ ]
      mode: bulk
      api_version: v8
      compression: gzip
      healthcheck:
        enabled: false
      request:
        headers:
          VL-Stream-Fields: source_type,label.com.docker.compose.service
          VL-Time-Field: timestamp
          VL-Msg-Field: message,msg,_msg,message.message,message.log
          AccountID: "0"
          ProjectID: "0"