{{ if .Capabilities.APIVersions.Has "postgresql.cnpg.io/v1" }}
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: grafana
spec:
  schedule: "0 0 0 * * *"
  backupOwnerReference: self
  cluster:
    name: grafana
{{ end }}