{{ if .Capabilities.APIVersions.Has "external-secrets.io/v1beta1" }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: grafana-cnpg
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: grafana-cnpg
spec:
  provider:
    vault:
      server: "http://vault-active.vault:8200"
      path: kv
      version: v2
      auth:
        kubernetes:
          mountPath: kubernetes
          role: grafana-cnpg
          serviceAccountRef:
            name: grafana-cnpg
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafana-cnpg
spec:
  secretStoreRef:
    name: grafana-cnpg
    kind: SecretStore
  target:
    name: grafana-cnpg
  data:
    - remoteRef:
        key: grafana-cnpg/secrets
        property: init-sql
      secretKey: init-sql
    - remoteRef:
        key: grafana-cnpg/secrets
        property: region
      secretKey: aws-region
    - remoteRef:
        key: grafana-cnpg/secrets
        property: access-key
      secretKey: access-key
    - remoteRef:
        key: grafana-cnpg/secrets
        property: secret-key
      secretKey: secret-key
{{ end }}