{{ if .Capabilities.APIVersions.Has "external-secrets.io/v1beta1" }}
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: grafana-oidc
spec:
  provider:
    vault:
      server: "http://vault-active.vault:8200"
      path: kv
      version: v2
      auth:
        kubernetes:
          mountPath: kubernetes
          role: grafana
          serviceAccountRef:
            name: grafana
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafana-oidc
spec:
  secretStoreRef:
    name: grafana-oidc
    kind: SecretStore
  target:
    name: grafana-oidc
  data:
    - remoteRef:
        key: grafana/secrets
        property: oidc-icon
      secretKey: oidc-icon
    - remoteRef:
        key: grafana/secrets
        property: oidc-id
      secretKey: oidc-id
    - remoteRef:
        key: grafana/secrets
        property: oidc-secret
      secretKey: oidc-secret
    - remoteRef:
        key: grafana/secrets
        property: oidc-url
      secretKey: oidc-url
    - remoteRef:
        key: grafana/secrets
        property: oidc-url-authorize
      secretKey: oidc-url-authorize
    - remoteRef:
        key: grafana/secrets
        property: oidc-url-token
      secretKey: oidc-url-token
    - remoteRef:
        key: grafana/secrets
        property: oidc-url-userinfo
      secretKey: oidc-url-userinfo
{{ end }}