apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: &name argo-rollouts
spec:
  source:
    repoURL: https://argoproj.github.io/argo-helm
    chart: *name
    targetRevision: 2.39.6
  destination:
    server: "https://kubernetes.default.svc"
    namespace: *name
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
      - ApplyOutOfSyncOnly=true
    retry:
      limit: 3
      backoff:
        duration: 15s
        factor: 2
        maxDuration: 3m
