apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: &name kube-prometheus-stack
spec:
  sources:
    - repoURL: https://prometheus-community.github.io/helm-charts
      chart: *name
      targetRevision: 75.9.0
      helm:
        valueFiles:
          - $values/manifests-values/kube-prometheus-stack/values.yaml
    - repoURL: https://github.com/ifbreadgood/k8s-base
      targetRevision: HEAD
      ref: values
  destination:
    server: "https://kubernetes.default.svc"
    namespace: *name
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
      - ApplyOutOfSyncOnly=true
    retry:
      limit: 3
      backoff:
        duration: 15s
        factor: 2
        maxDuration: 3m
