apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: argo-events
spec:
  parentRefs:
    - name: trial-studio-gateway
      namespace: istio-ingress
  hostnames: ["argo-events.trial.studio"]
  rules:
    - backendRefs:
        - name: gitea-eventsource-svc
          port: 12000