apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: gitea
spec:
  eventBusName: cicd
  template:
    serviceAccountName: operate-workflow-sa
  dependencies:
    - eventName: gitea
      eventSourceName: gitea
      name: gitea
  triggers:
    - template:
        name: first
        argoWorkflow:
          operation: submit
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: cicd-
              spec:
                workflowTemplateRef:
                  name: testing
                  clusterScope: false
#          parameters:
#            - src:
#                dependencyName: test-dep
#                contextKey: type
#              dest: spec.arguments.parameters.0.value