apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: gitea
spec:
  eventBusName: cicd
  service:
    ports:
      - port: 12000
        targetPort: 12000
  webhook:
    gitea:
      port: "12000"
      endpoint: /webhook
      method: POST
#---
#apiVersion: argoproj.io/v1alpha1
#kind: Workflow
#metadata:
#  name: ss
#spec:
#  templates:
#    - name: joe
#      steps:
#        - - name: what
#            template: yow