apiVersion: v2
name: vault
description: A Helm chart to set up hashicorp vault
type: application
version: 0.1.0
appVersion: "0.1.0"
dependencies:
  - name: vault
    version: 0.30.0
    repository: https://helm.releases.hashicorp.com