{{ if .Capabilities.APIVersions.Has "external-secrets.io/v1beta1" }}
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: tempo
spec:
  provider:
    vault:
      server: "http://vault-active.vault:8200"
      path: kv
      version: v2
      auth:
        kubernetes:
          mountPath: kubernetes
          role: tempo
          serviceAccountRef:
            name: tempo
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: tempo
spec:
  secretStoreRef:
    name: tempo
    kind: SecretStore
  target:
    name: tempo
  data:
    - remoteRef:
        key: tempo/secrets
        property:  access-key
      secretKey:  access_key
    - remoteRef:
        key: tempo/secrets
        property: region
      secretKey: s3_region
    - remoteRef:
        key: tempo/secrets
        property:  secret-key
      secretKey:  secret_key
    - remoteRef:
        key: tempo/secrets
        property:  endpoint
      secretKey:  endpoint
{{ end }}